name: Timothy W Evans
favicon: null
layout_spectrum: 0.22188223991543055
typography_spectrum: 0.6123136691749096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7054284706246108
  lightness: 0.19743111985735595
  saturation: 0.6196982669644058
  rhythmicContrast: 0.6493475746829063
purpose: []
